shell.executable("/bin/bash")
shell.prefix("source ~/.bash_profile; ")
import os 

""" Snakefile for running 10x pipeline """
# cellranger directory added to .bashrc 

configfile: "config_181114.yaml"

PROJECT = config ["PROJECT"]
RAW_DATA = config["RAW_DATA"]
DATA = config["DATA"]
SAMPLES = config["SAMPLES"]
TRANSCRIPTOME = config["TRANSCRIPTOME"]
EXPT_GROUPS = config["EXPT_GROUPS"]
MAX_10X_JOBS = config["MAX_10X_JOBS"]
LSF_TEMPLATE = config["LSF_TEMPLATE"]

rule all:
    input:
      expand("{data}/results/logs/{sample}_complete.txt", data = DATA,
        sample = SAMPLES),
#      expand("{data}/results/logs/{expt_groups}_aggr_complete.out.txt", 
#        data = DATA, expt_groups = EXPT_GROUPS),

include: "rules/10x_count.snake"
