---
title: "Neoplastic cells"
author: "Kent Riemondy RBI"
date: "9/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libs, message=FALSE, warning=FALSE, echo=FALSE}
source("../R/utils.R")
library(future)

plan("multicore", workers = 7)
options(future.globals.maxSize = 2 * 1024 ^ 3)

proj_dir <- here()
data_dir <- file.path(proj_dir, "data", "cellranger", "results")
doc_dir <- file.path(proj_dir, "docs")

fig_dir <- "figs"
mkrs_dir <- "markers"
tbls_dir <- "tables"
xcel_dir <- file.path(mkrs_dir, "xlsx")
walk(c(fig_dir, mkrs_dir, tbls_dir, xcel_dir), 
     dir.create, 
     showWarnings = F)
```



```{r}
so <- readRDS(file.path("objects", "so.rds"))
```


```{r}
malignant_cells <- colnames(so)[so$coarse_cell_type == "malignant"]

so <- so[, malignant_cells]


so <- FindVariableFeatures(
  so,
  selection.method = "vst",
  nfeatures = 3000,
  verbose = FALSE
)

so <- ScaleData(so, features = VariableFeatures(so), 
                  vars.to.regress = c("percent.mt", "nCount_RNA"), 
                  verbose = TRUE)

so <- RunPCA(so, 
             features = VariableFeatures(so),
             npcs = 100, 
             verbose = FALSE)

ElbowPlot(so, ndims = 100)

# make graphs and use graphs for UMAP
so <- FindNeighbors(so, 
                      reduction = "pca", 
                      dims = 1:50, 
                      k.param = 50L)


so <- RunUMAP(so, 
              graph = "RNA_snn", 
              min.dist = 0.4)

so <- FindClusters(so, 
                   resolution = c(0.1, 0.3, 0.5))

so$coarse_clusters_malignant <- so$RNA_snn_res.0.1

Idents(so) <- "coarse_clusters_malignant"


plot_umap(so, "coarse_clusters_malignant")

plot_umap(so, "subgroup")
```

## Compare to Cavatelli subgroups

```{r, fig.width = 18, fig.height = 8}
array_mdata <- read.table(file.path(doc_dir,
                                    "microarray_data",
                                    "2019_09_04_tidy_CEL_annotation_file_for_Cavalli_2012.txt"),
                          stringsAsFactors = FALSE) %>% 
  as_tibble() %>% 
  mutate(Subtype = str_trim(Subtype))

array_mat <- read.table(file.path(doc_dir,
                                    "microarray_data",
                                "2019_09_04_expression_data_all_medullo_Cavalli_GEO_numbers.txt"),
                        stringsAsFactors = FALSE) %>% 
  as_tibble()

# average probesets
expr_mat <- array_mat %>% 
  gather("key", "value", -sym) %>% 
  group_by(sym, key) %>% 
  summarize(value = mean(value)) %>%
  spread(key, value) %>%
  as.data.frame() %>% 
  column_to_rownames("sym") %>% 
  as.matrix()

# average probesets across subtypes
avg_mat <- unique(array_mdata$Subtype) %>% 
  map(function(x){
    cols <- array_mdata[which(array_mdata$Subtype == x), 
                   "GEO_number", 
                   drop = TRUE]
    
    vals <- rowMeans(expr_mat[, cols])
    res <- tibble(sym = names(vals))
    res[[x]] <- vals
    res
    }) %>% 
  Reduce(function(x, y) {left_join(x, y, by = "sym")}, .) %>% 
  as.data.frame() %>% 
  column_to_rownames("sym") %>% 
  as.matrix()

library(clustifyr)

res <- clustify(so, ref_mat = avg_mat, cluster_col = "coarse_clusters", seurat_out = FALSE) %>% 
  cor_to_call(.) %>% 
  left_join(rownames_to_column(so@meta.data, "cell"), .,
            by = c("coarse_clusters" = "cluster")) %>% 
  dplyr::select(cell, 
                subtype = type, 
                subtype_cor = r) %>% 
  as.data.frame() %>% 
  column_to_rownames("cell")

so <- AddMetaData(so, res)
a <- plot_umap(so, "subtype")
b <- plot_umap(so, "subgroup")
d <- plot_umap(so, "UPN")
plot_grid(a, b, d, nrow = 1)
```


```{r}
saveRDS(so, "objects/all_neoplastic.rds")
```


```{r markers of each subgroup}
so <- readRDS("objects/all_neoplastic.rds")

Idents(so) <- "subgroup"

mkrs <- FindAllMarkers(so, only_pos = TRUE)

write_tsv(mkrs, 
          file.path(mkrs_dir, "subgroup_markers_neoplastic.tsv"))

write_markers_xlsx(split(mkrs, mkrs$cluster),
                   file.path(xcel_dir, "subgroup_markers_neoplastic.xlsx"))
```

```{r markers of each patient sample}
so <- readRDS("objects/all_neoplastic.rds")

Idents(so) <- "UPN"

mkrs <- FindAllMarkers(so, only_pos = TRUE)

write_tsv(mkrs, 
          file.path(mkrs_dir, "upn_markers_neoplastic.tsv"))

write_markers_xlsx(split(mkrs, mkrs$cluster),
                   file.path(xcel_dir, "upn_markers_neoplastic.xlsx"))

mkrs <- FindAllMarkers(so, only_pos = FALSE)

write_tsv(mkrs, 
          file.path(mkrs_dir, "upn_markers_neoplastic_pos_and_neg.tsv"))

write_markers_xlsx(split(mkrs, mkrs$cluster),
                   file.path(xcel_dir, "upn_markers_neoplastic_pos_and_neg.xlsx"))
```

## Get top PC genes

```{r}
to_plot <- c("UPN", "coarse_cell_type", "subgroup")

dims_to_plot <- list(
  c(1,2),
  c(2,3),
  c(3,4),
  c(4,5))
  
plts <- list()
for ( i in seq_along(dims_to_plot)){
  plts[[i]] <- map(to_plot, ~plot_pca(so, .x, dims =dims_to_plot[[i]])) %>%
  plot_grid(plotlist = ., nrow = 1, ncol = length(to_plot),
            rel_widths = c(1.75, 1.5, 1))
}

names(plts) <- str_c("pc_", 
                     map_chr(dims_to_plot, ~str_c(.x, collapse = "_")),
                     ".pdf")
pc_dir <- file.path(fig_dir, "pcs_all_neoplastic")
dir.create(pc_dir)
iwalk(plts,
  ~save_plot(file.path(pc_dir, .y), .x, nrow = 1, ncol = 3))


pc_loadings <- so@reductions$pca@feature.loadings[, 1:20] %>% 
  as.data.frame() %>% 
  tibble::rownames_to_column("gene") %>% 
  arrange(desc(PC_1))

pc_tbl_dir <- file.path(tbls_dir, "pcs", "all_neoplastic")
dir.create(pc_tbl_dir, recursive = TRUE)
write_tsv(pc_loadings, file.path(pc_tbl_dir, "pc_loadings.tsv.gz"))

tibble(pc = str_c("PC", 1:length(so@reductions$pca@stdev)), 
                  stdev = so@reductions$pca@stdev) %>% 
  write_tsv(file.path(pc_tbl_dir, "pc_variance_explained.tsv"))

```
