---
title: "figs2"
author: "Kent Riemondy RBI"
date: "8/22/2019"
output: html_document
---

```{r libs, message=FALSE, warning=FALSE, echo=FALSE}
source("../R/utils.R")
library(future)
plan(strategy = "multicore", workers = 6)
options(future.globals.maxSize = 2 * 1024 ^ 3)

proj_dir <- here()
data_dir <- file.path(proj_dir, "data", "cellranger", "results")
doc_dir <- file.path(proj_dir, "docs")

fig_dir <- "figs"
mkrs_dir <- "markers"
tbls_dir <- "tables"
walk(c(fig_dir, mkrs_dir, tbls_dir), dir.create, showWarnings = F)

library(ComplexHeatmap)
library(dendextend)
```

## Plot cell distibutions per subgroup and tumor

```{r}
so <- readRDS(file.path("objects", "so.rds"))
```

```{r}
sc_mdata <- so@meta.data %>% 
  rownames_to_column("cell")

per_patient <- sc_mdata %>% 
  mutate(simple_id = ifelse(coarse_cell_type == "malignant",
                            "Malignant",
                            coarse_cell_type)) %>% 
  group_by(UPN) %>%
  mutate(n_cells = n()) %>% 
  group_by(UPN, simple_id) %>% 
  summarize(n = n(),
            prop_cell_type = n / unique(n_cells),
            subgroup = as.character(unique(subgroup)))

ggplot(per_patient, 
       aes(UPN, prop_cell_type)) +
  geom_col(aes(fill = simple_id)) +
  facet_wrap(~subgroup, scales = "free_x") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

## Examine NMF factorization

## cNMF
```{r, eval = FALSE}
so <- readRDS(file.path("objects", "so.rds"))

count_mat <- GetAssayData(so, "counts")

count_mat <- count_mat[, colnames(so)]
to_keep_genes <- rowSums(count_mat > 0) > (ncol(count_mat) * 0.001)
count_mat <- count_mat[to_keep_genes, ]

count_mat <- t(count_mat)

count_mat <- as.data.frame(as.matrix(count_mat))
# dimensions ~20K genes by 45K cells

write.table(count_mat, file.path("tables", "full_count_matrix.tsv"), sep = "\t")
```

examine cNMF output

```{r}
so <- readRDS(file.path("objects", "so.rds"))


file_dir <- "cNMF/full_data_cnmf/cnmf_2/"
files <- dir(file_dir, pattern = ".txt", full.names = TRUE) %>% 
  str_subset(., "k_12")
file_dat <- map(files, read_tsv)
```

```{r}

gep_usages <- file_dat[[4]]

colnames(gep_usages) <- c("cell", 
                          paste0("GEP_", 1:(length(colnames(gep_usages)) - 1)))

max_scores <- apply(gep_usages[, 2:ncol(gep_usages)], 1, function(x) sum(x))
gep_usages[, 2:ncol(gep_usages)] <- gep_usages[, 2:ncol(gep_usages)] / max_scores


so <- so[, gep_usages$cell]

so@meta.data <- so@meta.data %>% 
  rownames_to_column("cell") %>% 
  left_join(gep_usages, by = "cell") %>% 
  column_to_rownames("cell")

p <- map(paste0("GEP_", 1:12), 
    ~plot_feature(so, .x, embedding = "umap")) %>% 
  plot_grid(plotlist = . , nrow = 4)

p
```


```{r}

to_plot <- so@meta.data %>% 
  group_by(coarse_clusters) %>% 
  summarize_at(.vars = vars(starts_with("GEP")), .funs = mean) %>% 
  as.data.frame() %>% 
  column_to_rownames("coarse_clusters") %>% 
  as.matrix()

ComplexHeatmap::Heatmap(to_plot, 
                        cluster_columns = FALSE)




to_plot <- so@meta.data %>% 
  group_by(subgroup) %>% 
  summarize_at(.vars = vars(starts_with("GEP")), .funs = mean) %>% 
  as.data.frame() %>% 
  column_to_rownames("subgroup") %>% 
  as.matrix()

ComplexHeatmap::Heatmap(to_plot, 
                        cluster_columns = FALSE)

```

```{r}
gene_score <- file_dat[[1]] 
gene_score <- rename(gene_score, cluster = X1) %>% 
  gather(gene, score, -cluster)

gene_score %>% 
  group_by(cluster) %>% 
  arrange(desc(score), .by_group = TRUE) %>% 
  slice(1:50) %>%
  filter(cluster == 2) %>% 
  View()
```



## scHPF
```{r, eval = FALSE}
library(rtracklayer)
# need ensembl ids and suggest keeping only protein coding

gtf_fn <- "../dbases/genes.gtf"
symbol2id <- import(gtf_fn) %>% 
  as.data.frame() 

symbol2id <- symbol2id %>% 
  select(gene_id, gene_name, gene_biotype) %>% 
  unique() %>% 
  filter(gene_biotype == "protein_coding")

so <- readRDS(file.path("objects", "so.rds"))

count_mat <- GetAssayData(so, "counts")

count_mat <- count_mat[, colnames(so)]

# keep genes expressed in at least 0.1%
to_keep_genes <- rowSums(count_mat > 0) > (ncol(count_mat) * 0.001)

count_mat <- count_mat[to_keep_genes, ]

# keep only protein coding

count_mat <- count_mat[which(rownames(count_mat) %in% symbol2id$gene_name), ]

count_mat <- as.data.frame(as.matrix(count_mat))

# add in ensembl ids
count_mat <- tibble::rownames_to_column(count_mat, "gene")
count_mat <- left_join(count_mat, symbol2id, by = c("gene" = "gene_name"))
count_mat <- select(count_mat, gene_id, gene, -gene_biotype, everything())



# subset to single tumors to run

upns <- unique(as.character(so$UPN))
outdir <- file.path("tables", "schpf")

dir.create(outdir, showWarnings = FALSE)
walk(upns,
     function(upn){
       cells_to_keep <- colnames(so)[so$UPN == upn & so$coarse_cell_type == "malignant"]
       
       out_mat <- count_mat[, c("gene_id", "gene", cells_to_keep)]
       
       dir.create(file.path(outdir, upn), 
                  showWarnings = FALSE)
       # add ensembl id to first col, then gene, then counts
       write_tsv(out_mat,
                file.path(outdir, upn, "count_matrix.tsv"),
                 col_names = FALSE)
})

rm(count_mat)

Sys.setenv(SAMPLES = paste0(file.path(outdir, upns[2:length(upns)]),
                            collapse = " "))
```




```{bash}
eval "$(/miniconda3/condabin/conda shell.bash hook)"
conda activate schpf_p37

#for i in $SAMPLES
#do echo $i
#bn=$(basename $i)
##scHPF prep -i $i"/count_matrix.tsv" -o $i -m 5 
##scHPF train -i $i"/train.mtx" -o $i -k 5 -t 5 
#scHPF score -m $i/"scHPF_K5_epsilon0.001_5trials.joblib" \
#            -o $i \
#            -p $bn".k5" \
#            -g $i/"genes.txt"
#
#done


for i in $SAMPLES
do echo $i
bn=$(basename $i)
#scHPF prep -i $i"/count_matrix.tsv" -o $i -m 5 
scHPF train -i $i"/train.mtx" -o $i -k 4 -t 5 
scHPF score -m $i/"scHPF_K4_epsilon0.001_5trials.joblib" \
            -o $i \
            -p $bn".k4" \
            -g $i/"genes.txt"

done

for i in $SAMPLES
do echo $i
bn=$(basename $i)
#scHPF prep -i $i"/count_matrix.tsv" -o $i -m 5 
scHPF train -i $i"/train.mtx" -o $i -k 3 -t 5 
scHPF score -m $i/"scHPF_K3_epsilon0.001_5trials.joblib" \
            -o $i \
            -p $bn".k3" \
            -g $i/"genes.txt"

done

```

### Metafactors

```{r}
files <- file.path(outdir, 
                   upns[2:length(upns)], 
                   paste0( upns[2:length(upns)],
                           ".ranked_genes.txt"))

ranked_genes <- map(files, read_tsv, col_names = paste0("factor_", 1:5))
names(ranked_genes) <-  upns[2:length(upns)]

# get gene scores 
gs_files <- file.path(outdir, 
                   upns[2:length(upns)], 
                   paste0( upns[2:length(upns)],
                           ".gene_score.txt"))

gene_id_files <- file.path(outdir, 
                   upns[2:length(upns)], 
                   "genes.txt")
  
# make simple ids for cols
mdata <- so@meta.data %>% 
  select(UPN, subgroup) %>% 
  unique() %>% 
  mutate(id = str_c(UPN, "_", subgroup)) %>% 
  mutate_if(is.factor, as.character)

ids <- mdata$id
names(ids) <- mdata$UPN

gs_dat <- pmap(list(gs_files,
               gene_id_files,
                upns[2:length(upns)]),
               function(x, y, z){
  gs_df <- read_tsv(x, col_names = str_c("m_", ids[z], "_factor_", 1:5)) %>% 
    as.data.frame()
  genes <- read_tsv(y, col_names = c("ens_id", "gene_name"))
  # make unique to match seurat handling of duplicate gene names
  gs_df$gene <- make.unique(genes$gene_name)
  gs_df
  })

names(gs_dat) <- upns[2:length(upns)]
```

```{r}
correlate_metaprograms <- function(gene_scores_list,
                             ranked_genes_list,
                             n_genes = 50,
                             k_clusters = 5) {
  topx_union <- map(ranked_genes_list,
                    function(x) {
                      # get top and bottom 50
                      n <- nrow(x)
                      top_n_bottom <- x[c(1:n_genes, ((n - n_genes - 1):n)),]
                      unname(unlist(top_n_bottom))
                    }) %>%
    unlist(.) %>%
    unique(.)
  
  # merge all factors
  gs_dat_merged <- map(
    gene_scores_list,
    ~ left_join(tibble(gene = topx_union),
                .x,
                by = "gene") %>%
      as.data.frame(.) %>%
      column_to_rownames("gene")
  ) %>%
    unname() %>% 
    do.call(cbind, .) %>%
    na.omit(.) %>%
    as.matrix(.)
  
  
  factor_cor <- cor(gs_dat_merged,
                    method = "pearson")
  
  hc <- hclust(dist(factor_cor),
               method = "ward.D2")
  
  hc <- as.dendrogram(hc)
  hc_order <- order.dendrogram(hc)
  clusts <- dendextend::cutree(hc, k = k_clusters)
  clusts <- clusts[hc_order]
  hc <- color_branches(hc, clusters = clusts, groupLabels = TRUE)
  
  
  annot_df <- data.frame(
    row.names = colnames(factor_cor),
    subgroup = str_split(colnames(factor_cor),
                         "_",
                         simplify = TRUE) %>% .[, 3],
    meta_factors = clusts[colnames(factor_cor)]
  )
  
  cols <-  discrete_palette_default[unique(annot_df$subgroup)]
  names(cols) <- levels(annot_df$subgroup)
  
  factor_cols <- RColorBrewer::brewer.pal(k_clusters, "Set1")
  names(factor_cols) <- unique(clusts)
  
  column_ha <- HeatmapAnnotation(df = annot_df,
                                 col = list(subgroup = cols,
                                            meta_factors = factor_cols))
  
  hm <- Heatmap(
    factor_cor,
    col = viridis::viridis(256),
    cluster_columns = hc,
    cluster_rows = hc,
    show_column_dend = FALSE,
    bottom_annotation = column_ha
  )
  
  list(factor_df = gs_dat_merged,
       clusters = clusts,
       heatmap = hm)
}
```


```{r}
merge_metaprograms <- function(clusters,
                               factor_df) {
  
  meta_factors <- sapply(split(clusters, clusters),
                         function(clust) {
                           f_ids <- names(clust)
                           mat <- factor_df[, f_ids]
                           f_means <- rowMeans(mat, na.rm = TRUE)
                           f_means
                         })
  
  g_ids <- rownames(meta_factors)
  ranked_genes <- apply(meta_factors, 2, function(x) {
    g_ids[order(x, decreasing = TRUE)]
  }) %>%
    as.data.frame(stringsAsFactors = FALSE)
  
  list(ranked_genes= ranked_genes,
       meta_factors = meta_factors)
}

```


```{r}
mp <- correlate_metaprograms(gs_dat, top_genes, n_genes = 50, k_clusters = 5)

print(mp$heatmap)
```

```{r}
metaprog <- merge_metaprograms(mp$clusters, mp$factor_df)
metaprog$ranked_genes[1:10, ]
```

Identify meta factors

```{r}

for (i in 1:ncol(metaprog$ranked_genes)){
  
  so <- AddModuleScore(so, 
                       features = list(c(metaprog$ranked_genes[1:50, i, drop = TRUE])),
                       ctrl = 50,
                       name = str_c("MB_metafactor_", i, "_"),
                       seed = i)
}

map(str_c("MB_metafactor_", 1:ncol(metaprog$ranked_genes), "_1"),
    ~plot_umap(so, .x, show_negative = TRUE)) %>% 
  plot_grid(plotlist = ., nrow = 3, ncol = 2)

```

### Parse out by subgroup

### SHH


```{r}

shh_ids <- filter(mdata, subgroup == "SHH") %>% pull(UPN) %>% as.character()
shh_ids <- shh_ids[shh_ids != "1008"]
shh_mp <- correlate_metaprograms(gene_scores_list = gs_dat[shh_ids],  
                                ranked_genes_list = top_genes[shh_ids], 
                                n_genes = 50, k_clusters = 5)

print(shh_mp$heatmap)
```

```{r}
shh_metaprog <- merge_metaprograms(shh_mp$clusters, shh_mp$factor_df)
shh_metaprog$ranked_genes
```


```{r}

for (i in 1:ncol(shh_metaprog$ranked_genes)){
  
  so <- AddModuleScore(so, 
                       features = list(c(shh_metaprog$ranked_genes[1:50, i, drop = TRUE])),
                       ctrl = 50,
                       name = str_c("SHH_metafactor_", i, "_"),
                       seed = i)
}

map(str_c("SHH_metafactor_", 1:ncol(shh_metaprog$ranked_genes), "_1"),
    ~plot_umap(so, .x, show_negative = TRUE)) %>% 
  plot_grid(plotlist = ., nrow = 3, ncol = 2)

```

### Group 3, 3/4, 4

```{r}

gp34_ids <- filter(mdata, subgroup != "SHH") %>% pull(UPN) %>% as.character()
gp34_ids <- gp34_ids[gp34_ids != "1028"]

gp34_mp <- correlate_metaprograms(gene_scores_list = gs_dat[gp34_ids],  
                                ranked_genes_list = top_genes[gp34_ids], 
                                n_genes = 50, k_clusters = 4)

print(gp34_mp$heatmap)
```

```{r}
gp34_metaprog <- merge_metaprograms(gp34_mp$clusters, gp34_mp$factor_df)
gp34_metaprog$ranked_genes
```


```{r}

for (i in 1:ncol(gp34_metaprog$ranked_genes)){
  
  so <- AddModuleScore(so, 
                       features = list(c(gp34_metaprog$ranked_genes[1:50, i, drop = TRUE])),
                       ctrl = 50,
                       name = str_c("GP34_metafactor_", i, "_"),
                       seed = i)
}

map(str_c("GP34_metafactor_", 1:ncol(gp34_metaprog$ranked_genes), "_1"),
    ~plot_umap(so, .x, show_negative = TRUE)) %>% 
  plot_grid(plotlist = ., nrow = 3, ncol = 2)

```


```{r, try_pca_to_define_malignant}
chrom_annots <- symbol2id %>% arrange(seqnames, start) %>% select(chrom = seqnames, gene_name) %>% unique()
chrom_annots <- filter(chrom_annots, gene_name %in% rownames(so))
chrom_genes <- split(chrom_annots, chrom_annots$chrom)

# just use autosomes and break into 100 gene chunks per chrom
chrom_gene_partitions <- map(chrom_genes[1:22], ~split(.x$gene_name, ceiling(seq_along(.x$gene_name)/100)) )
chrom_gene_partitions <- unlist(chrom_gene_partitions, recursive = FALSE)
chrom_gene_partitions <- chrom_gene_partitions[map_lgl(chrom_gene_partitions, ~length(.x) > 50)]

dat <- GetAssayData(so, "data")


per_chrom_expr <- sapply(chrom_gene_partitions, function(x) expm1(dat[x, , drop = FALSE])  %>% colMeans(.) %>% log1p(.))

p <- prcomp(per_chrom_expr, center = TRUE, scale. = TRUE)

pcs <- as.data.frame(p$x)

mdata <- so@meta.data %>% 
  rownames_to_column("cell")

pcs <- pcs %>% 
  rownames_to_column("cell") %>% 
  left_join(mdata) 

ggplot(pcs, aes(PC1, PC2)) + geom_point(aes(color = coarse_cell_type))
  
```



## Subset immune populations


```{r}
  
immune_cells <- colnames(so)[so$coarse_cell_type %in% c("t-cells",
                                                        "b-cells", 
                                                        "macrophage_monocytes")]

so <- so[, immune_cells]
so <- FindVariableFeatures(so, 
                             selection.method = "vst", 
                             nfeatures = 3000, 
                             verbose = FALSE)

so <- ScaleData(so, 
                  vars.to.regress = c("percent.mt", "nCount_RNA"), 
                  verbose = TRUE)

so <- RunPCA(so, npcs = 40, verbose = FALSE)

so <- FindNeighbors(so,
                      reduction = "pca",
                      dims = 1:20,
                      k.param = 20)

so <- RunUMAP(so, graph = "RNA_snn")


so <- FindClusters(so, resolution = c(0.3, 0.1, 0.05, 0.02, .01))


so$fine_immune_clusters <- so$RNA_snn_res.0.3


clusters <- so$fine_immune_clusters

so$refined_immune_clusters <- ifelse(clusters %in% c("2", "3", "5", "6",
                                                     "7", "9"),
                                     "macrophage_monocytes",
                                     ifelse(clusters %in% c("4"),
                                            "b-cells",
                                            ifelse(clusters %in% c("0",
                                                                   "1",
                                                                   "11","10"),
                                                   "t-cells",
                                                   ifelse(clusters == "8",
                                                          "macrophage_monocytes_minor",
                                                          "unknown"))))

```


```{r}
outdir <- "figs/normal_subset"
dir.create(outdir, showWarnings = FALSE)

plts <- map(str_subset(colnames(so@meta.data), "RNA_snn"), 
            ~plot_umap(so, .x) + 
              labs(title = .x))

p_1 <- plot_umap(so, "subgroup") + labs(title = "Subgroup")
p_2 <- plot_umap(so, "cell_type") + labs(title = "Cell Type")
plts <- c(plts, list(p_1), list(p_2))

plt <- plot_grid(plotlist = plts, nrow = 3, ncol = 3)
save_plot(file.path(outdir, "umaps_by_resolution.pdf"), 
          plt, 
          nrow = 3, ncol = 3)


plts <- map(c("subgroup", "UPN", "cell_type"),
    ~plot_umap(so, .x))

plt <- plot_grid(plotlist = plts, nrow = 1, ncol = 3)
save_plot(file.path(outdir, "umaps_by_class.pdf"), 
          plt, 
          nrow = 1, ncol = 3)
```

## save object

```{r }
saveRDS(so, file.path("objects", "immune_sobj_v2.rds"))
```


## Markers within cluster

```{r, eval = F}
Idents(so) <- "refined_immune_clusters"

mkrs_between_samples <- map(unique(sort(so$refined_immune_clusters)), 
    function(x) {
      
      tmp_obj <- subset(so, idents = x)
      Idents(tmp_obj) <- "subgroup"
      mkrs <- FindAllMarkers(tmp_obj,
                          only.pos = TRUE) %>% 
         filter(p_val_adj < 0.01)
      mkrs
    })

names(mkrs_between_samples) <- unique(sort(so$refined_immune_clusters))

mkrs_between_samples_df <- bind_rows(mkrs_between_samples, 
                                  .id = "cluster")
write_tsv(mkrs_between_samples_df, 
          file.path(mkrs_dir, "immune_subset_cluster_markers_between_subgroups.tsv"))

openxlsx::write.xlsx(mkrs_between_samples, 
                      file.path(mkrs_dir, "immune_subset_cluster_markers_between_subgroups.xlsx"))
```

```{r}
## reload object

so <- readRDS(file.path("objects", "immune_sobj_v2.rds"))

so_sub <- subset(so, 
                 subset = refined_immune_clusters == "macrophage_monocytes")

mkrs <- FindMarkers(so_sub, 
                    ident.1 = "GP4", 
                    ident.2 = "SHH", 
                    group.by = "subgroup")

mkrs <- tibble::rownames_to_column(mkrs, "gene")

write_tsv(mkrs, 
          file.path(mkrs_dir, 
                    "macrophage_markers_between_gp4_shh.tsv"))
```

```{r}

mkrs <- arrange(mkrs, 
                p_val_adj)
up_mkrs <- filter(mkrs, avg_logFC > 0) %>% slice(1:50)
down_mkrs <- filter(mkrs, avg_logFC < 0) %>% slice(1:50)

top_mkrs <- bind_rows(up_mkrs, down_mkrs)

library(ComplexHeatmap)

Idents(so_sub) <- "subgroup"

to_plot <- log1p(AverageExpression(so_sub)$RNA)
to_plot <- to_plot[top_mkrs$gene, ] 

to_plot <- t(scale(t(as.matrix(to_plot))))

hm <- Heatmap(to_plot, col = viridis::viridis(256),
        name = "Z-score")

pdf("macrophages_differences_between_subgroups.pdf", height = 16)
print(hm)
dev.off()


xcel_out <- list()
xcel_out$macrophages <- mkrs
```


```{r}
so_sub <- subset(so, 
                 subset = refined_immune_clusters == "t-cells")

mkrs <- FindMarkers(so_sub, 
                    ident.1 = "GP4", 
                    ident.2 = "SHH", 
                    group.by = "subgroup")

mkrs <- tibble::rownames_to_column(mkrs, "gene")

write_tsv(mkrs, 
          file.path(mkrs_dir, 
                    "tcells_markers_between_gp4_shh.tsv"))

```

```{r}

mkrs <- arrange(mkrs, 
                p_val_adj)
up_mkrs <- filter(mkrs, avg_logFC > 0) %>% slice(1:50)
down_mkrs <- filter(mkrs, avg_logFC < 0) %>% slice(1:50)

top_mkrs <- bind_rows(up_mkrs, down_mkrs)

library(ComplexHeatmap)

Idents(so_sub) <- "subgroup"

to_plot <- log1p(AverageExpression(so_sub)$RNA)
to_plot <- to_plot[top_mkrs$gene, ] 

to_plot <- t(scale(t(as.matrix(to_plot))))

hm <- Heatmap(to_plot, col = viridis::viridis(256),
        name = "Z-score")

pdf("t-cell_differences_between_subgroups.pdf", height = 16)
print(hm)
dev.off()


xcel_out$t_cells <- mkrs

xcel_out <- map(xcel_out, 
                       ~set_xlsx_class(.x, "gene", "Text"))

openxlsx::write.xlsx(xcel_out, 
                     "markers_v2/shh_gp4_immune_cell_differences.xlsx")
```


```{r}
to_plot <- c("refined_immune_clusters", 
"subgroup",
  "UPN")

plts <- map(to_plot, ~plot_umap(so, .x))



plt <- plot_grid(plotlist = plts, nrow = 2, ncol = 2,
                 rel_widths = c(1.75, 1.25))
save_plot("immune_population_umaps.pdf", plt, 
          nrow = 2, ncol = 2, base_asp = 1.2)


plts <- map(c("MRC1", "CCL3"), ~plot_umap(so, .x))


plt <- plot_grid(plotlist = plts, nrow = 1)
save_plot("immune_population_umaps_expr.pdf", plt, 
          nrow = 1, ncol = 2, base_asp = 1.2)

```
