---
title: "Group 3 and 4 analysis"
author: "Kent Riemondy RBI"
date: "9/26/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libs, message=FALSE, warning=FALSE, echo=FALSE}
source("../R/utils.R")
```



```{r}
so <- readRDS(file.path("objects", "all_neoplastic.rds"))
```


```{r}
gp_cells <- colnames(so)[so$subgroup != "SHH"]

so <- so[, gp_cells]

so <- FindVariableFeatures(
  so,
  selection.method = "vst",
  nfeatures = 3000,
  verbose = FALSE
)

so <- ScaleData(so, features = VariableFeatures(so), 
                  vars.to.regress = c("percent.mt", "nCount_RNA"), 
                  verbose = TRUE)

so <- RunPCA(so, 
             features = VariableFeatures(so),
             npcs = 100, 
             verbose = FALSE)

ElbowPlot(so, ndims = 100)

# make graphs and use graphs for UMAP
so <- FindNeighbors(so, 
                      reduction = "pca", 
                      dims = 1:50, 
                      k.param = 50L)


so <- RunUMAP(so, 
              dims = 1:50, 
              n.neighbors = 30L,
              min.dist = 0.4)

so <- FindClusters(so, 
                   resolution = c(0.1, 0.3, 0.5))

so$coarse_clusters_shh <- so$RNA_snn_res.0.1

Idents(so) <- "coarse_clusters_gp34"

plot_umap(so, "coarse_clusters_gp34")
plot_umap(so, "UPN")
plot_umap(so, "subtype")
```

## Harmonize

```{r}
library(harmony)
so <- RunHarmony(so,
                 "UPN", 
                 theta = 1.5,
                 plot_convergence = TRUE)

so <- RunUMAP(so, 
              reduction = "harmony", 
              dims = 1:40, 
              min.dist = 0.2,
              n.neighbors = 30L,
              reduction.name = "umap_harmony",
              reduction.key = "UMAP_Harmony_")

plot_feature(so, "UPN", embedding = "umap_harmony")
plot_umap(so, "UPN")
plot_umap(so, "subtype")

so <- FindNeighbors(so, reduction = "harmony", dims = 1:40)
so <- FindClusters(so, resolution = 0.2)




so$coarse_clusters_gp34_harmony <- so$seurat_clusters
Idents(so) <- "coarse_clusters_gp34_harmony"
plot_feature(so, "coarse_clusters_gp34_harmony", embedding = "umap_harmony")
```

```{r}
saveRDS(so, "objects/gp34.rds")
```


```{r markers of each subgroup}
so <- readRDS("objects/gp34.rds")

Idents(so) <- "coarse_clusters_gp34_harmony"

mkrs <- FindAllMarkers(so, only.pos = TRUE)

write_tsv(mkrs, 
          file.path(mkrs_dir, "harmony_markers_gp34.tsv"))

write_markers_xlsx(split(mkrs, mkrs$cluster),
                   file.path(xcel_dir, "harmony_markers_gp34.xlsx"))
```

## GO terms

```{r}
library(gprofiler2)
library(ggrepel)
mkrs <- read_tsv(file.path(mkrs_dir, 
                    "harmony_markers_gp34.tsv")) %>% 
  filter( p_val_adj < 0.05)

mkrs_split <- split(mkrs, mkrs$cluster) %>% 
  map(~pull(.x, gene))
go_res <- gost(mkrs_split, 
               ordered_query = TRUE,
               sources = c("GO", 
                          "KEGG", 
                          "REAC", 
                          "TF"))


go_res[["result"]] %>% 
  mutate(parents = unlist(map(parents, 
                              ~str_c(.x, collapse = ",")))) %>% 
  write_tsv(file.path(tbls_dir, "goterms_gp34_clusters.tsv"))

go_res[["result"]] %>% 
  mutate(parents = unlist(map(parents, 
                              ~str_c(.x, collapse = ","))),
         source = str_replace_all(source, 
                                  "[[:punct:]]", " ")) %>% 
  select(-significant) %>% 
  split(., .$query) %>% 
  openxlsx::write.xlsx(., file.path(tbls_dir, "goterms_gp34_cluster.xlsx"))
```

## Heatmap of gene expression

```{r}
topx <- read_tsv(file.path(mkrs_dir, 
                    "harmony_markers_gp34.tsv")) %>% 
  filter(p_val_adj < 0.05,
         cluster %in% as.character(c(0:5))) %>% 
  group_by(cluster) %>% 
  arrange(p_val_adj, .by_group = TRUE) %>% 
  slice(1:10)

so <- ScaleData(so, features = rownames(so))

tmp_so <- subset(so, 
                 subset = coarse_clusters_gp34_harmony %in% as.character(c(0:5)))

tmp_so$coarse_clusters_gp34_harmony <- factor(tmp_so$coarse_clusters_gp34_harmony)

p <- DoHeatmap(tmp_so, 
               group.colors = discrete_palette_default,
               features = unique(topx$gene),
               group.by = "coarse_clusters_gp34_harmony",
               angle = 0, 
               raster = FALSE, 
               draw.lines = TRUE)

p <- p +
  scale_fill_gradientn(colours = viridis::viridis(256),
                       name = "Expression\nZ-scores")

save_plot(file.path(fig_dir, "heatmap_markers_gp34.pdf"), 
          p,
          base_width = 10,
          base_height = 12)


```

## Heatmap by TF activity

```{r}
so_tf_markers <- read_tsv("tables/gp34_tf_activities.tsv")

topx <- so_tf_markers %>% 
  filter(cluster %in% as.character(c(0:5))) %>% 
  group_by(cluster) %>% 
  arrange(p_val_adj, .by_group = TRUE) %>% 
  slice(1:5)

DefaultAssay(tmp_so) <- "TF"
tmp_so <- ScaleData(tmp_so)

p <- DoHeatmap(tmp_so, 
               group.colors = discrete_palette_default,
        features = unique(topx$gene),
        group.by = "coarse_clusters_gp34_harmony",
        angle = 0, 
        raster = FALSE, 
        draw.lines = TRUE)

p <- p +
  scale_fill_gradientn(colours = viridis::viridis(256),
                       name = "Regulon AUC\nZ-scores")

save_plot(file.path(fig_dir, "heatmap_tfs_gp34.pdf"), 
          p,
          base_width = 10,
          base_height = 6)

rm(tmp_so)
DefaultAssay(so) <- "RNA"
```

## Add in Northcutt paper metamodule scores

```{r}
supp_tbl_2 <- "https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-019-1434-6/MediaObjects/41586_2019_1434_MOESM3_ESM.xlsx"


download.file(supp_tbl_2, "../docs/northcutt_sup_tbl_2.xlsx")
sup_tbl <- read_excel("../docs/northcutt_sup_tbl_2.xlsx", 
           sheet = 2,
           skip = 3) 

sup_tbl[, 1] <- NULL

# extract out each metaprogram following their approach of excluding ribosomal
# and protein genes and non-coding RNAs

mps <- map(seq(1, ncol(sup_tbl), 2), 
    ~c(.x, .x + 1)) %>% 
  map(., ~sup_tbl[, .x] 
      %>% na.omit()) 

mp_names <- map_chr(mps, ~colnames(.x)[2])
mps <- map(mps, ~.x[, 2, drop = TRUE]) 
names(mps) <- mp_names

gp34_mps <- mps[str_subset(names(mps), "Group")]
for (i in seq_along(gp34_mps)){
  so <- AddModuleScore(so, 
                       features = list(c(gp34_mps[[i]])),
                       ctrl = 50,
                       name = str_c( names(gp34_mps)[i], "_metafactor"),
                       seed = 42)
}

```


```{r}

so <- CellCycleScoring(so,
                       g2m.features = cc.genes$g2m.genes,
                       s.features = cc.genes$s.genes)
```


## Save object and write out matrix for other tools

```{r}
saveRDS(so, "objects/gp34.rds")
```

```{r}
so <- readRDS("objects/gp34.rds")

#full count matrix
GetAssayData(so, "counts") %>% 
  as.matrix(.) %>% 
  as.data.frame() %>% 
  rownames_to_column("gene") %>% 
  write_tsv("tables/gp34_count_matrix.tsv.gz")
  
# expression matrix filtered at least 25 cells express the gene
expr_mat <- GetAssayData(so, "data")
expr_mat <- expr_mat[Matrix::rowSums(expr_mat > 0) >= 25, ]

expr_mat %>% 
  as.matrix(.) %>% 
  as.data.frame() %>% 
  rownames_to_column("gene") %>% 
  write_tsv("tables/gp34_expr_matrix.tsv.gz")
  
```

save loom file for paga

```{r}

# drop graphs see https://github.com/theislab/scanpy/issues/598
tmp_obj <- readRDS("objects/gp34.rds")
tmp_obj@graphs <- list()
tmp_obj@meta.data <- tmp_obj@meta.data[, c("coarse_clusters_gp34_harmony",
                                           "orig.ident",
                                           "subtype",
                                           "subgroup",
                                           "UPN")]

lfile <- as.loom(tmp_obj,filename = file.path("objects", "grp34.loom"),
        verbose = TRUE,
        overwrite = TRUE)
lfile$close_all()

rm(tmp_obj)
```
