---
title: "gene_signatures"
author: "Kent Riemondy RBI"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "html") })
output:
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: false
    theme: cosmo
    highlight: tango
    fig_caption: true
    code_folding: hide
    df_print: paged
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libs}
source(here::here("/R/utils.R"))
library(ComplexHeatmap)
library(presto)
library(openxlsx)
library(gprofiler2)
library(ggrepel)
library(igraph)
library(GeneOverlap)
```


```{r}

so_fns <- file.path(obj_dir, c(
  file.path("shh", "shh.qs"),
  file.path("gp34", "gp3_only.qs"),
  file.path("gp34", "gp4_only.qs")))
                    
clusters <- c(
  "tumor_subpopulations_shh",
  "tumor_subpopulations_gp3",
  "tumor_subpopulations_gp4"
)

sos <- map(so_fns, 
            ~qread(.x, nthreads = 4, use_alt_rep = FALSE))

names(sos) <- c("SHH", "GP3", "GP4")

```

## Regenerate marker tables etc.

Using the new cell type labels

```{r}
all_mrkrs <- pmap(
  list(sos,
       names(sos),
       clusters
  ),
  function(so, id, cluster){
    
    mk_dir <- file.path(mkrs_dir, id)
    dir.create(mk_dir, showWarnings = FALSE)
    tbl_dir <- file.path(tbls_dir, id)
    dir.create(tbl_dir, showWarnings = FALSE)
    
    # markers
    full_mkrs <-  wilcoxauc(so, cluster) 
    
    mkrs <- filter(full_mkrs, logFC > 0, padj < 0.05, pct_in > 0.10) %>% 
      group_by(group) %>% 
      arrange(padj, desc(logFC), .by_group = TRUE)
    
    mkrs %>% 
      write_tsv(file.path(mk_dir, str_c("harmony_subpopulation_markers_", id, ".tsv")))
    
    mkrs %>% 
      ungroup() %>% 
      split(., .$group) %>% 
      write_markers_xlsx(., file.path(tbl_dir,
                                      str_c("harmony_subpopulation_markers_", id, ".xlsx")))
    
    # Go terms using top 500 markers 
    mkrs <- mkrs %>% 
      group_by(group) %>% 
      slice(1:500)  
    
    mkrs_split <- split(mkrs, mkrs$group) %>% 
      map(~pull(.x, feature))
    
    go_res <- gost(mkrs_split, 
                   ordered_query = TRUE,
                   sources = c("GO", 
                               "KEGG", 
                               "REAC", 
                               "TF"))
    
    go_res[["result"]] %>% 
      mutate(parents = unlist(map(parents, ~str_c(.x, collapse = ",")))) %>% 
      write_tsv(., file.path(tbl_dir, str_c("subpopulation_goterms_", id, ".tsv")))
    
    go_res[["result"]] %>% 
      mutate(parents = unlist(map(parents, ~str_c(.x, collapse = ","))),
             source = str_replace_all(source, "[[:punct:]]", " ")) %>% 
      select(-significant) %>% 
      split(., .$query) %>% 
      openxlsx::write.xlsx(., file.path(tbl_dir, 
                                        str_c("subpopulation_goterms_", id, ".xlsx")))
    
    ## Average Expression
    write_avg_expr(so,  
                   cluster,
                   file.path(tbl_dir, 
                             str_c("subpopulation_avgexpr_", id, ".csv")))
    ## Cell counts
    cell_count_mat <- get_cell_count_matrix(so, "UPN", cluster)
    cell_count_mat[is.na(cell_count_mat)] <- 0L
    cell_count_mat %>% 
      tibble::rownames_to_column("UPN") %>% 
      write_csv(file.path(tbl_dir, 
                          str_c("subpopulation_cell_counts_", id, ".csv")))
    
    ## marker matrix 
    full_marker_matrix <- full_mkrs %>%  top_marker_matrix(.) 
    
    topn_marker_matrix <- full_mkrs %>% top_marker_matrix(n = 200) 
    
    out <- list(avg_expression = read_csv(file.path(tbl_dir, 
                                                    str_c("subpopulation_avgexpr_", 
                                                          id,
                                                          ".csv"))),
                logFC_all = full_marker_matrix,
                top_200_logFC = topn_marker_matrix)
    
    openxlsx::write.xlsx(out, 
                         file.path(tbl_dir, 
                                   str_c("subpopulation_expression_logfc_summaries_",
                                         id,
                                         ".xlsx")))
    
    #full count matrix
    GetAssayData(so, "counts") %>% 
      as.matrix(.) %>% 
      as.data.frame() %>% 
      rownames_to_column("gene") %>% 
      data.table::fwrite(., file.path(tbl_dir, str_c(id, 
                                                     "_count_matrix.csv.gz")),
                         sep = ",",
                         compress = "gzip")
    
    # expression matrix filtered at least 25 cells express the gene
    expr_mat <- GetAssayData(so, "data")
    expr_mat <- expr_mat[Matrix::rowSums(expr_mat > 0) >= 25, ]
    
    expr_mat %>% 
      as.matrix(.) %>% 
      as.data.frame() %>% 
      rownames_to_column("gene") %>% 
      data.table::fwrite(., file.path(tbl_dir, str_c(id, "_expr_matrix.csv.gz")),
                         sep = ",",
                         compress = "gzip")
    
    ## TF markers
    Idents(so) <- cluster
    DefaultAssay(so) <- "TF"
    
    so_tf_markers <- wilcoxauc(so,
                               group_by = cluster, 
                               seurat_assay = "TF") %>% 
      filter(logFC > 0, 
             padj < 0.05) %>% 
      group_by(group) %>% 
      arrange(padj, desc(logFC))
    
    write_tsv(so_tf_markers, file.path(tbl_dir, 
                                       str_c("subpopulation_tf_activities_", id, ".tsv")))
    
    write_markers_xlsx(split(so_tf_markers, so_tf_markers$group),
                       path = file.path(tbl_dir, 
                                        str_c("subpopulation_tf_activities_", id, ".xlsx")),
                       description_string = "Transcription factor regulons derived from PyScenic that are significantly enriched in each cluster")
    
    mkrs
  })


```

```{r}

rmd_dir <- "cell_type_signature_comparisons"

fig_dir <- file.path(fig_dir, rmd_dir)
mkrs_dir <- file.path(mkrs_dir, rmd_dir)
tbls_dir <- file.path(tbls_dir, rmd_dir)
go_dir <- file.path(tbls_dir, "go")
xcel_markers_dir <- file.path(tbls_dir, "markers")

walk(c(fig_dir, mkrs_dir, tbls_dir, go_dir, xcel_markers_dir),
     dir.create, 
     showWarnings = FALSE)
```


```{r}
sos <- pmap(
  list(sos,
    names(sos),
    clusters),
            function(so, id, cluster){
              # drop the excluded populations
              to_keep <- rownames(so@meta.data)[!str_detect(so[[cluster]][,1], "-X[0-9]$")]
              so <- subset(so, cells = to_keep)
              so$tumor_cell_type <- so[[cluster]][,1]
              so
            })

avg_expr <- pmap(list(
  sos,
  names(sos),
  clusters),
           function(x, id, cluster){
            Idents(x) <- "tumor_cell_type"
             mat <- AverageExpression(x)$RNA
             x <- FindVariableFeatures(x, nfeatures = 2000)
             var_genes <- VariableFeatures(x)
             list(expr = mat,
                  var_genes = var_genes)
           })


var_genes <- map(avg_expr, ~.x$var_genes) %>% 
  unlist() %>% 
  unique()

avg_expr_mat <- map(avg_expr, ~.x$expr) %>% 
  unname() %>% 
  do.call(cbind, .)

avg_expr_mat <- avg_expr_mat[var_genes, ]


hmap <- Heatmap(cor(avg_expr_mat, method = "pearson"),
        col = viridis::viridis(256),
        name = "Correlation",
        row_names_gp = gpar(fontsize = 7),
        column_names_gp = gpar(fontsize = 7))

pdf(file.path(fig_dir, "tumor_subpopulation_correlation_matrix.pdf"),
    width = 9,
    height = 7)
draw(hmap)
dev.off()

hmap
```


```{r}
so <- merge(sos[[1]], sos[2:3])
```


```{r}
var_marker_lst <- all_mrkrs %>%
  map(~group_by(.x, group) %>% slice(1:100)) %>% 
  bind_rows() %>% 
  split(., .$group) %>% 
  map(~pull(.x, feature))

var_marker_lst <- var_marker_lst[!str_detect(names(var_marker_lst),  "-X[0-9]$")]


for(i in seq_along(var_marker_lst)){
  mrks <- var_marker_lst[[i]]
  id <- names(var_marker_lst)[i]
  so <- AddModuleScore(so, list(x = mrks), assay = "RNA", name = id, seed = 42)
}

# rename cols
col_idxs <- match(str_c(make.names(names(var_marker_lst)), "1"), 
                    colnames(so@meta.data))
colnames(so@meta.data)[col_idxs] <- str_c(names(var_marker_lst), "-signature")

all_tumor_cell_expression_scores <- get_metadata(so, embedding = NULL) %>% 
  .[, c("cell", str_c(names(var_marker_lst), "-signature"))] %>% 
  column_to_rownames("cell") %>% 
  as.matrix()

hmap <- Heatmap(cor(all_tumor_cell_expression_scores, method = "spearman"),
         col = viridis::viridis(256),
        name = "Correlation",
        row_names_gp = gpar(fontsize = 7),
        column_names_gp = gpar(fontsize = 7))

pdf(file.path(fig_dir, "tumor_subpopulation_scores_all_tumor_cells_cor_matrix.pdf"),
    width = 9,
    height = 7)
  draw(hmap)
dev.off()

hmap
```


## Make graphs based on correlation 

```{r}
so_gp3 <- qread(file.path("objects", "gp34", "gp3_only.qs"))
so_gp4 <- qread(file.path("objects", "gp34", "gp4_only.qs"))
so_shh <- qread(file.path("objects", "shh", "shh.qs")) 
  

gp4_to_keep <- colnames(so_gp4)[!str_detect(so_gp4$tumor_subpopulations_gp4, "X") ]
so_gp4 <- subset(so_gp4, cells = gp4_to_keep)

shh_to_keep <- colnames(so_shh)[so_shh$tumor_subpopulations_shh != "SHH-X1"]
so_shh <- subset(so_shh, cells = shh_to_keep)

sos <- list(
  gp3 = so_gp3,
  gp4 = so_gp4,
  shh = so_shh
)

rm(so_gp3, so_gp4, so_shh)
```

```{r}
avg_objs <- map2(
  sos,
  c("tumor_subpopulations_gp3",
    "tumor_subpopulations_gp4",
    "tumor_subpopulations_shh"),
  function(x, cluster_col) {
    Idents(x) <- cluster_col  
    avg_expr <- AverageExpression(x, return.seurat = FALSE)$RNA
    var_features <- VariableFeatures(FindVariableFeatures(x, nfeatures = 2000))
    list(expr = avg_expr, var_genes = var_features)
  })
```

```{r}
var_genes <- map(avg_objs, ~.x$var_genes) %>% 
  unlist() %>% 
  unique()

var_genes <- Reduce(intersect, map(avg_objs, ~.x$var_genes))

avg_expr_mat <- map(avg_objs, ~.x$expr) %>% 
  unname() %>% 
  do.call(cbind, .)

avg_expr_mat <- avg_expr_mat[var_genes, ]


hmap <- Heatmap(cor(avg_expr_mat, method = "pearson"),
        col = viridis::viridis(256),
        name = "Correlation",
        row_names_gp = gpar(fontsize = 7),
        column_names_gp = gpar(fontsize = 7))

pdf(file.path(fig_dir, "tumor_subpopulation_correlation_matrix.pdf"),
    width = 9,
    height = 7)
draw(hmap)
dev.off()
```


```{r}
pairwise_comps <- list(
  c("gp3", "gp4"),
  c("shh", "gp3"),
  c("shh", "gp4")
)

get_cor_values <- function(x, y, 
                           gene_combine_function = intersect,
                           cor_method = "spearman"){ 
  shared_var_genes <- gene_combine_function(x$var_genes, y$var_genes)
  
  x_mat <- x$expr[shared_var_genes, ] 
  
  y_mat <-  y$expr[shared_var_genes, ] 
  
  res <- list()
  res$r <- matrix(nrow = ncol(y_mat),
                  ncol = ncol(x_mat))
  res$pvals <- res$r
  
  for(m in seq_along(colnames(y_mat))){
    for(h in seq_along(colnames(x_mat))){
      s <- cor.test(y_mat[, m], x_mat[, h], method = cor_method)
      res$r[m, h] <- s$estimate
      res$pvals[m,h] <- s$p.value
    }
  }
  
  res$padj <- matrix(p.adjust(res$pvals),
                     nrow = nrow(res$pvals), 
                     ncol = ncol(res$pvals),
                     byrow = FALSE)
  res <- map(res, ~{
    rownames(.x) <- colnames(y_mat)
    colnames(.x) <- colnames(x_mat)
    .x
  })
  
  res
}
```


### GP3 vs. GP4

```{r}
res <- get_cor_values(avg_objs[["gp3"]], avg_objs[["gp4"]])
seed_val <- 20200613

# weighted graph based on correlation
g <- graph.incidence(res$r, weighted = TRUE)

# prune edges with correlation < 0.8 similar to clustifyr (or non-sig)
g <- delete_edges(g, which(E(g)$weight <= max(res$r) * 0.8 | as.vector(t(res$padj)) >= 0.05))

# add some meta clusters
set.seed(seed_val)
wc <- cluster_walktrap(g)

V(g)$color <- V(g)$type
V(g)$shape <- ifelse(V(g)$type, "circle", "rectangle")

# force directed layout
set.seed(seed_val)
layout <- layout.fruchterman.reingold(g)

new_cols <- ifelse(startsWith(V(g)$name, "GP3"), "white", "black")

min_cor <- min(E(g)$weight)
max_cor <- max(E(g)$weight)
plot(wc, g,
     col = new_cols,
     mark.col = alpha(palette_OkabeIto[1:length(groups(wc))], 0.75),
     mark.border = "black",
     layout = layout,
    edge.width= scales::rescale(E(g)$weight, c(1,5)), 
     vertex.label = str_replace(V(g)$name, "-", "\n"),
     vertex.label.family = "sans",
    vertex.label.color = ifelse(startsWith(V(g)$name, "GP3"), "black", "white"))

legend("bottomleft",
       legend = c(paste("r =", formatC(min_cor, digits = 2)),
                  paste("r =", formatC(max_cor, digits = 2))),
       lwd = c(min(scales::rescale(E(g)$weight, c(1,5))),
               max(scales::rescale(E(g)$weight, c(1,5)))))
       

pdf(file.path(fig_dir,
              "gp3_to_gp4_correlation_graph.pdf"),
    height = 9, width = 9)
plot(wc, g,
     col = new_cols,
     mark.col = alpha(palette_OkabeIto[1:length(groups(wc))], 0.75),
     mark.border = "black",
     layout = layout,
    edge.width= scales::rescale(E(g)$weight, c(1,5)), 
     vertex.label = str_replace(V(g)$name, "-", "\n"),
     vertex.label.family = "sans",
    vertex.label.color = ifelse(startsWith(V(g)$name, "GP3"), "black", "white"))

legend("bottomleft",
       legend = c(paste("r =", formatC(min_cor, digits = 2)),
                  paste("r =", formatC(max_cor, digits = 2))),
       lwd = c(min(scales::rescale(E(g)$weight, c(1,5))),
               max(scales::rescale(E(g)$weight, c(1,5)))))
       
dev.off()
```


### GP3 vs. SHH

```{r}
res <- get_cor_values(avg_objs[["gp3"]], avg_objs[["shh"]])
seed_val <- 20200613

# weighted graph based on correlation
g <- graph.incidence(res$r, weighted = TRUE)

# prune edges with correlation < 0.8 similar to clustifyr (or non-sig)
g <- delete_edges(g, which(E(g)$weight <= max(res$r) * 0.8 | as.vector(t(res$padj)) >= 0.05))

# add some meta clusters
set.seed(seed_val)
wc <- cluster_walktrap(g)

V(g)$color <- V(g)$type
V(g)$shape <- ifelse(V(g)$type, "circle", "rectangle")

# force directed layout
set.seed(seed_val)
layout <- layout.fruchterman.reingold(g)

new_cols <- ifelse(startsWith(V(g)$name, "GP3"), "white", "black")

min_cor <- min(E(g)$weight)
max_cor <- max(E(g)$weight)
plot(wc, g,
     col = new_cols,
     mark.col = alpha(palette_OkabeIto[1:length(groups(wc))], 0.75),
     mark.border = "black",
     layout = layout,
    edge.width= scales::rescale(E(g)$weight, c(1,5)), 
     vertex.label = str_replace(V(g)$name, "-", "\n"),
     vertex.label.family = "sans",
    vertex.label.color = ifelse(startsWith(V(g)$name, "GP3"), "black", "white"))

legend("bottomleft",
       legend = c(paste("r =", formatC(min_cor, digits = 2)),
                  paste("r =", formatC(max_cor, digits = 2))),
       lwd = c(min(scales::rescale(E(g)$weight, c(1,5))),
               max(scales::rescale(E(g)$weight, c(1,5)))))
       

pdf(file.path(fig_dir,
              "gp3_to_shh_correlation_graph.pdf"),
    height = 9, width = 9)
plot(wc, g,
     col = new_cols,
     mark.col = alpha(palette_OkabeIto[1:length(groups(wc))], 0.75),
     mark.border = "black",
     layout = layout,
    edge.width= scales::rescale(E(g)$weight, c(1,5)), 
     vertex.label = str_replace(V(g)$name, "-", "\n"),
     vertex.label.family = "sans",
    vertex.label.color = ifelse(startsWith(V(g)$name, "GP3"), "black", "white"))

legend("bottomleft",
       legend = c(paste("r =", formatC(min_cor, digits = 2)),
                  paste("r =", formatC(max_cor, digits = 2))),
       lwd = c(min(scales::rescale(E(g)$weight, c(1,5))),
               max(scales::rescale(E(g)$weight, c(1,5)))))
       
dev.off()
```



```{r}
library("GeneOverlap")

mouse_markers <- read_tsv(file.path("markers", "mouse", "gp34", "myc_gfi1_malignant_cluster_markers.tsv")) %>% 
filter(padj < 0.05) %>% 
  group_by(group) %>% 
  arrange(padj, desc(logFC), .by_group = TRUE) %>% 
  inner_join(orthologs, by = c("feature" = "mmusculus_homolog_associated_gene_name")) %>% 
    slice(1:200) %>% 
  split(., .$group) %>% 
  map(~pull(.x, external_gene_name))

human_markers <- read_tsv(file.path("markers", "GP3",  "harmony_subpopulation_markers_GP3.tsv")) %>% 
  filter(padj < 0.05) %>% 
  group_by(group) %>% 
  arrange(padj, desc(logFC), .by_group = TRUE) %>% 
  semi_join(orthologs, by = c("feature" = "external_gene_name")) %>% 
  slice(1:200) %>% 
  split(., .$group) %>% 
  map(~pull(.x, feature))


gom_human_mouse <- newGOM(mouse_markers, 
                       human_markers,
                       genome.size = nrow(so_sub))

# extract overlaps
pvals  <- getMatrix(gom_human_mouse, c("pval")) 
pvals <- apply(pvals, 2, function(x) p.adjust(x, n = length(pvals)))

jaccard <- getMatrix(gom_human_mouse, "Jaccard")
odds <- getMatrix(gom_human_mouse, c("odds.ratio"))

library(ComplexHeatmap)
# clip really low pvals to avoid take log10 of 0)
clip_val <- 1e-300
  
pvals[pvals < clip_val] <- clip_val
pvals <- -log10(pvals)

Heatmap(pvals,
        name = "-log10(pvalue)", 
        col = viridis::viridis(256),
        row_title = "Mouse model markers",
        column_title = "Human Group 3 and 4 markers")

h <- Heatmap(jaccard,
        name = "Jaccard index", 
        col = viridis::viridis(256),
       row_title = "Myc + GFI1 model clusters",
        column_title = "Human Group 3 and 4 clusters",
        cell_fun = function(j, i, x, y, width, height, fill) {
          bin <- findInterval(pvals[i, j], c(-log10(0.01), 20, 200))
          txt <- c("*", "**", "***")[bin]
          grid.text(txt, x, y, gp = gpar(fontsize = 10, col = "white"))
})


lgd_list <-  list(
    Legend(labels = c("*** < 1e-200",
                      "** < 1e-20",
                      "* < 1e-2"), 
           title = "Adj. p.val")
)
draw(h, heatmap_legend_list = lgd_list)


pdf(file.path(fig_dir, "Marker_overlap_gfi1_malignant_gp34.pdf"),
    width = 7,
    height = 7)
  draw(h, heatmap_legend_list = lgd_list)
dev.off()
```


### GP4 vs. SHH

```{r}
res <- get_cor_values(avg_objs[["gp4"]], avg_objs[["shh"]])
seed_val <- 20200613


# weighted graph based on correlation
g <- graph.incidence(res$r, weighted = TRUE)

# prune edges with correlation < 0.8 similar to clustifyr (or non-sig)
g <- delete_edges(g, which(E(g)$weight <= max(res$r) * 0.8 | as.vector(t(res$padj)) >= 0.05))

# add some meta clusters
set.seed(seed_val)
wc <- cluster_walktrap(g)

V(g)$color <- V(g)$type
V(g)$shape <- ifelse(V(g)$type, "circle", "rectangle")

# force directed layout
set.seed(seed_val)
layout <- layout.fruchterman.reingold(g)

new_cols <- ifelse(startsWith(V(g)$name, "GP4"), "white", "black")

min_cor <- min(E(g)$weight)
max_cor <- max(E(g)$weight)
plot(wc, g,
     col = new_cols,
     mark.col = alpha(palette_OkabeIto[1:length(groups(wc))], 0.75),
     mark.border = "black",
     layout = layout,
    edge.width= scales::rescale(E(g)$weight, c(1,5)), 
     vertex.label = str_replace(V(g)$name, "-", "\n"),
     vertex.label.family = "sans",
    vertex.label.color = ifelse(startsWith(V(g)$name, "GP4"), "black", "white"))

legend("bottomleft",
       legend = c(paste("r =", formatC(min_cor, digits = 2)),
                  paste("r =", formatC(max_cor, digits = 2))),
       lwd = c(min(scales::rescale(E(g)$weight, c(1,5))),
               max(scales::rescale(E(g)$weight, c(1,5)))))
       

pdf(file.path(fig_dir,
              "gp4_to_shh_correlation_graph.pdf"),
    height = 9, width = 9)
plot(wc, g,
     col = new_cols,
     mark.col = alpha(palette_OkabeIto[1:length(groups(wc))], 0.75),
     mark.border = "black",
     layout = layout,
    edge.width= scales::rescale(E(g)$weight, c(1,5)), 
     vertex.label = str_replace(V(g)$name, "-", "\n"),
     vertex.label.family = "sans",
    vertex.label.color = ifelse(startsWith(V(g)$name, "GP4"), "black", "white"))

legend("bottomleft",
       legend = c(paste("r =", formatC(min_cor, digits = 2)),
                  paste("r =", formatC(max_cor, digits = 2))),
       lwd = c(min(scales::rescale(E(g)$weight, c(1,5))),
               max(scales::rescale(E(g)$weight, c(1,5)))))
       
dev.off()
```


## Marker overlap 

### GP3 vs GP4 

```{r}
gp3_markers <- read_tsv(file.path("markers", "GP3", "harmony_subpopulation_markers_GP3.tsv")) %>% 
  filter(padj < 0.05,
         !str_detect(group, "X")) %>% 
  group_by(group) %>% 
  arrange(padj, desc(logFC), .by_group = TRUE) %>% 
  slice(1:200) %>% 
  split(., .$group) %>% 
  map(~pull(.x, feature))

gp4_markers <- read_tsv(file.path("markers", "GP4",  "harmony_subpopulation_markers_GP4.tsv")) %>% 
  filter(padj < 0.05,
         !str_detect(group, "X")) %>% 
  group_by(group) %>% 
  arrange(padj, desc(logFC), .by_group = TRUE) %>%
  slice(1:200) %>% 
  split(., .$group) %>% 
  map(~pull(.x, feature))


gom <- newGOM(gp3_markers, 
              gp4_markers,
              genome.size = nrow(sos$gp3))

# extract overlaps
pvals  <- getMatrix(gom, c("pval")) 
pvals <- apply(pvals, 2, function(x) p.adjust(x, n = length(pvals)))

jaccard <- getMatrix(gom, "Jaccard")
odds <- getMatrix(gom, c("odds.ratio"))


# clip really low pvals to avoid take log10 of 0)
clip_val <- 1e-300
  
pvals[pvals < clip_val] <- clip_val
pvals <- -log10(pvals)

h <- Heatmap(jaccard,
        name = "Jaccard index", 
        col = viridis::viridis(256),
       row_title = "Group 3 subpopulations",
        column_title = "Group 4 subpopulations",
        cell_fun = function(j, i, x, y, width, height, fill) {
          bin <- findInterval(pvals[i, j], c(-log10(0.01), 20, 200))
          txt <- c("*", "**", "***")[bin]
          grid.text(txt, x, y, gp = gpar(fontsize = 10, col = "white"))
})


lgd_list <-  list(
    Legend(labels = c("*** < 1e-200",
                      "** < 1e-20",
                      "* < 1e-2"), 
           title = "Adj. p.val")
)
draw(h, heatmap_legend_list = lgd_list)


pdf(file.path(fig_dir, "Marker_overlap_gp3_gp4.pdf"),
    width = 7,
    height = 7)
  draw(h, heatmap_legend_list = lgd_list)
dev.off()
```

### GP3 vs SHH 

```{r}
shh_markers <- read_tsv(file.path("markers", "SHH",  "harmony_subpopulation_markers_SHH.tsv")) %>% 
  filter(padj < 0.05,
         !str_detect(group, "X")) %>% 
  group_by(group) %>% 
  arrange(padj, desc(logFC), .by_group = TRUE) %>%
  slice(1:200) %>% 
  split(., .$group) %>% 
  map(~pull(.x, feature))


gom <- newGOM(gp3_markers, 
              shh_markers,
              genome.size = nrow(sos$gp3))

# extract overlaps
pvals  <- getMatrix(gom, c("pval")) 
pvals <- apply(pvals, 2, function(x) p.adjust(x, n = length(pvals)))

jaccard <- getMatrix(gom, "Jaccard")
odds <- getMatrix(gom, c("odds.ratio"))


# clip really low pvals to avoid take log10 of 0)
clip_val <- 1e-300
  
pvals[pvals < clip_val] <- clip_val
pvals <- -log10(pvals)

h <- Heatmap(jaccard,
        name = "Jaccard index", 
        col = viridis::viridis(256),
       row_title = "Group 3 subpopulations",
        column_title = "SHH subpopulations",
        cell_fun = function(j, i, x, y, width, height, fill) {
          bin <- findInterval(pvals[i, j], c(-log10(0.01), 20, 200))
          txt <- c("*", "**", "***")[bin]
          grid.text(txt, x, y, gp = gpar(fontsize = 10, col = "white"))
})


lgd_list <-  list(
    Legend(labels = c("*** < 1e-200",
                      "** < 1e-20",
                      "* < 1e-2"), 
           title = "Adj. p.val")
)
draw(h, heatmap_legend_list = lgd_list)


pdf(file.path(fig_dir, "Marker_overlap_gp3_shh.pdf"),
    width = 7,
    height = 7)
  draw(h, heatmap_legend_list = lgd_list)
dev.off()
```

### GP3 vs GP4 

```{r}
gom <- newGOM(gp4_markers, 
              shh_markers,
              genome.size = nrow(sos$gp4))

# extract overlaps
pvals  <- getMatrix(gom, c("pval")) 
pvals <- apply(pvals, 2, function(x) p.adjust(x, n = length(pvals)))

jaccard <- getMatrix(gom, "Jaccard")
odds <- getMatrix(gom, c("odds.ratio"))


# clip really low pvals to avoid take log10 of 0)
clip_val <- 1e-300
  
pvals[pvals < clip_val] <- clip_val
pvals <- -log10(pvals)

h <- Heatmap(jaccard,
        name = "Jaccard index", 
        col = viridis::viridis(256),
       row_title = "Group 4 subpopulations",
        column_title = "SHH subpopulations",
        cell_fun = function(j, i, x, y, width, height, fill) {
          bin <- findInterval(pvals[i, j], c(-log10(0.01), 20, 200))
          txt <- c("*", "**", "***")[bin]
          grid.text(txt, x, y, gp = gpar(fontsize = 10, col = "white"))
})


lgd_list <-  list(
    Legend(labels = c("*** < 1e-200",
                      "** < 1e-20",
                      "* < 1e-2"), 
           title = "Adj. p.val")
)
draw(h, heatmap_legend_list = lgd_list)


pdf(file.path(fig_dir, "Marker_overlap_gp4_shh.pdf"),
    width = 7,
    height = 7)
  draw(h, heatmap_legend_list = lgd_list)
dev.off()
```

## Other analyses

```{r, eval = FALSE}
all_tumor_mkrs <- wilcoxauc(so, "tumor_cell_type")

undiff_pops <- str_subset(unique(so$tumor_cell_type), "_Undifferentiated")
undiff_mkrs <- wilcoxauc(so, "tumor_cell_type", groups_use = undiff_pops)

top_undiff_mkrs <- undiff_mkrs %>% 
  filter(padj < 0.05,
                       logFC > 0, 
                       pct_in > 0.10) %>% 
  group_by(group) %>% 
  arrange(padj, desc(logFC), .by_group = T) %>% 
  ungroup()


diff_pops <- str_subset(unique(so$tumor_cell_type), "_Differentiated")
diff_mkrs <- wilcoxauc(so, "tumor_cell_type", groups_use = diff_pops)

top_diff_mkrs <- diff_mkrs %>% 
  filter(padj < 0.05,
                       logFC > 0, 
                       pct_in > 0.10) %>% 
  group_by(group) %>% 
  arrange(padj, desc(logFC), .by_group = T) %>% 
  ungroup()

top_diff_mkrs <- split(top_diff_mkrs, top_diff_mkrs$group) 
names(top_diff_mkrs) <- names(top_diff_mkrs) %>% 
   str_remove("_Differentiated") %>% 
  str_replace_all("[[:punct:]]", "")

write.xlsx(top_diff_mkrs, file.path(xcel_markers_dir,
                                    "tumor_differentiated_population_markers.xlsx")) 

top_undiff_mkrs <- split(top_undiff_mkrs, top_undiff_mkrs$group) 
names(top_undiff_mkrs) <- names(top_undiff_mkrs) %>% 
   str_remove("_Undifferentiated") %>% 
  str_replace_all("[[:punct:]]", "")

write.xlsx(top_undiff_mkrs, file.path(xcel_markers_dir,
                                    "tumor_undifferentiated_population_markers.xlsx")) 
```


```{r, eval = FALSE}
# Use top 500 markers   
mkrs_split <- map(top_undiff_mkrs, ~pull(.x[1:500, ], feature))

go_res <- gost(mkrs_split, 
               ordered_query = TRUE,
               sources = c("GO", 
                          "KEGG", 
                          "REAC", 
                          "TF"))

go_res[["result"]] %>% 
  mutate(parents = unlist(map(parents, ~str_c(.x, collapse = ","))),
         source = str_replace_all(source, "[[:punct:]]", " ")) %>% 
  select(-significant) %>% 
  split(., .$query) %>% 
  openxlsx::write.xlsx(., file.path(go_dir, "goterms_undifferentiated_cell_types.xlsx"))



mkrs_split <- map(top_diff_mkrs, ~pull(.x[1:500, ], feature))

go_res <- gost(mkrs_split, 
               ordered_query = TRUE,
               sources = c("GO", 
                          "KEGG", 
                          "REAC", 
                          "TF"))

go_res[["result"]] %>% 
  mutate(parents = unlist(map(parents, ~str_c(.x, collapse = ","))),
         source = str_replace_all(source, "[[:punct:]]", " ")) %>% 
  select(-significant) %>% 
  split(., .$query) %>% 
  openxlsx::write.xlsx(., file.path(go_dir, "goterms_differentiated_cell_types.xlsx"))
```

```{r, eval = FALSE}
mkrs <- diff_mkrs %>% 
  filter(padj < 0.05,
         logFC > 0, 
         pct_in > 0.10) %>% 
  group_by(group) %>% 
  arrange(padj, desc(logFC), .by_group = T) %>% 
  # mutate(group = factor(group, levels = ))
  slice(1:10) %>% 
  pull(feature)

tmp <- subset(so, 
              subset = tumor_cell_type %in% c(
                "SHH_Differentiated (GRIA2, GOLGA8A, MALAT1) #1",
                "SHH_Differentiated (STMN2/4, MLLT1, NHLH1/2) #4",
                "GP3_Differentiated (GOLGA8A, MALAT1) #0",
                "GP3_Differentiated Photoreceptor (NRL) #2",
                "GP4_Differentiated (GRIA2, GOLGA8A, MALAT1) #0",
                "GP4_Differentiated Photoreceptor (NRL) #5")
)

tmp@assays$TF <- NULL
tmp <- ScaleData(tmp, features = mkrs)

hmap <- plot_heatmap(tmp, 
             features = unique(mkrs),
             group = "tumor_cell_type",
             average = TRUE, 
             hmap_options = list(show_column_names = FALSE, 
                                 cluster_columns = TRUE,
                                 cluster_rows = FALSE)
    )

pdf(file.path(fig_dir, "top_markers_between_differentiated_populations.pdf"),
    width = 7,
    height = 9)
draw(hmap)
dev.off()

hmap



mkrs <- undiff_mkrs %>% 
  filter(padj < 0.05,
                       logFC > 0, 
                       pct_in > 0.10) %>% 
  group_by(group) %>% 
  arrange(padj, desc(logFC), .by_group = T) %>% 
 # mutate(group = factor(group, levels = ))
  slice(1:10) %>% 
  pull(feature)

tmp <- subset(so, 
              subset = tumor_cell_type %in% c(
                "SHH_Undifferentiated (RPGs and SFRP1) #0",
                "SHH_Undifferentiated (RPGs and BTF3) #2",
                "GP3_Undifferentiated (RPGs and BTF3) #1",
                "GP3_Undifferentiated (MYC, FOXQ1/F2) #4",
                "GP4_Undifferentiated (RPGs, STMN1/2, EOMES) #1",
                "GP4_Undifferentiated (RPGs, STMN1/2) #2")
)

tmp@assays$TF <- NULL
tmp <- ScaleData(tmp, features = mkrs)

hmap <- plot_heatmap(tmp, 
             features = unique(mkrs),
             group = "tumor_cell_type",
             average = TRUE, 
             hmap_options = list(show_column_names = FALSE, 
                                 cluster_columns = TRUE,
                                 cluster_rows = TRUE)
    )

pdf(file.path(fig_dir, "top_markers_between_progenitor_populations.pdf"),
    width = 7,
    height = 9)
draw(hmap)
dev.off()

hmap

```


### Cell cycle differences

```{r, eval = FALSE}
plts <- plot_feature(sos$GP4, c("tumor_cell_type", 
                        "Phase",
                        "MKI67",
                        "GRIA2",
                        "RPL32"),
             embedding = "pca")

p <- plot_grid(plotlist = plts[2:5],
  nrow = 2, 
  ncol = 2)

p

save_plot(file.path(fig_dir, "gp4_cell_cycle_pca.pdf"),
          p,
          nrow = 2,
          ncol = 2,
          base_asp = 1.5)

p <- plot_grid(plotlist = plts[1],
  nrow = 1, 
  ncol = 1)

p

save_plot(file.path(fig_dir, "gp4_cell_type_pca.pdf"),
          p,
          nrow = 1,
          ncol = 1,
          base_asp = 2.5)


p <- plot_harmony(sos$GP4, "tumor_cell_type", legend_title = "")

save_plot(file.path(fig_dir, "gp4_cell_type_umap.pdf"),
          p,
          base_asp = 2.5)
```


```{r, eval = FALSE}

plts <- plot_feature(sos$GP3, c("tumor_cell_type", 
                        "Phase",
                        "MKI67",
                        "PCDH9",
                        "RPL32"),
             embedding = "pca")

p <- plot_grid(plotlist = plts[2:5],
  nrow = 2, 
  ncol = 2)

p

save_plot(file.path(fig_dir, "gp3_cell_cycle_pca.pdf"),
          p,
          nrow = 2,
          ncol = 2,
          base_asp = 1.5)

p <- plot_grid(plotlist = plts[1],
  nrow = 1, 
  ncol = 1)

p

save_plot(file.path(fig_dir, "gp3_cell_type_pca.pdf"),
          p,
          nrow = 1,
          ncol = 1,
          base_asp = 2.5)

p <- plot_harmony(sos$GP3, "tumor_cell_type", legend_title = "")

save_plot(file.path(fig_dir, "gp3_cell_type_umap.pdf"),
          p,
          base_asp = 2.5)
```



```{r, eval = FALSE}

plts <- plot_feature(sos$SHH, c("tumor_cell_type", 
                        "Phase",
                        "MKI67",
                        "NHLH1",
                        "RPL32"),
             embedding = "pca")

p <- plot_grid(plotlist = plts[2:5],
  nrow = 2, 
  ncol = 2)

p

save_plot(file.path(fig_dir, "shh_cell_cycle_pca.pdf"),
          p,
          nrow = 2,
          ncol = 2,
          base_asp = 1.5)

p <- plot_grid(plotlist = plts[1],
  nrow = 1, 
  ncol = 1)

p

save_plot(file.path(fig_dir, "shh_cell_type_pca.pdf"),
          p,
          nrow = 1,
          ncol = 1,
          base_asp = 2.5)


p <- plot_harmony(sos$SHH, "tumor_cell_type", legend_title = "")

save_plot(file.path(fig_dir, "shh_cell_type_umap.pdf"),
          p,
          base_asp = 2.5)
```

