---
title: "Subset to malignant and immune cells"
author: "Kent Riemondy RBI"
date: "`r Sys.Date()`"
params:
  ncores: 4
output:
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: false
    theme: cosmo
    highlight: tango
    fig_caption: true
    code_folding: hide
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
```

```{r libs, message=FALSE, warning=FALSE, echo=FALSE}
source("../R/utils.R")
library(future)
message(paste0("using ", params$ncores))

plan("multicore", workers = as.numeric(params$ncores))
options(future.globals.maxSize = 2 * 1024 ^ 3)

proj_dir <- here()
data_dir <- file.path(proj_dir, "data", "cellranger", "results")
doc_dir <- file.path(proj_dir, "docs")

fig_dir <- "figs"
mkrs_dir <- "markers"
walk(c(fig_dir,mkrs_dir), dir.create, showWarnings = F)
```

```{r get_data}
sobj <- readRDS(file.path("objects", "sobj.rds"))
```

```{r, fig.width = 12, fig.height = 12}

malignant_cells <- colnames(sobj)[sobj$cell_phenotype == "Neoplastic"]

sobj <- sobj[, malignant_cells]
sobj <- FindVariableFeatures(sobj, 
                             selection.method = "vst", 
                             nfeatures = 3000, 
                             verbose = FALSE)

sobj <- ScaleData(sobj, 
                  vars.to.regress = c("percent.mt", "nCount_RNA"), 
                  verbose = TRUE)

sobj <- RunPCA(sobj, npcs = 40, verbose = FALSE)
sobj <- RunUMAP(sobj, 
                reduction = "pca", 
                dims = 1:40, 
                min.dist = 0.3, 
                n.neighbors = 30L)

sobj <- FindNeighbors(sobj,
                      reduction = "pca",
                      dims = 1:40,
                      k.param = 50)

sobj <- FindClusters(sobj, 
                     resolution = c(0.3, 0.1, 0.05, 
                                    0.02, .01, 0.0075, 
                                    0.005))

plot_feature(sobj, "subgroup", embedding = "umap")
plot_feature(sobj, "UPN", embedding = "umap")
plot_feature(sobj, "seurat_clusters", embedding = "umap")

outdir <- "figs/malignant_subset"
dir.create(outdir, showWarnings = FALSE)

plts <- map(str_subset(colnames(sobj@meta.data), "RNA_snn"), 
            ~plot_umap(sobj, .x) + 
              labs(title = .x))

p_1 <- plot_umap(sobj, "subgroup") + labs(title = "Subgroup")

plts <- c(plts, list(p_1))

plt <- plot_grid(plotlist = plts, nrow = 3, ncol = 3)
save_plot(file.path(outdir, "umaps_by_resolution.pdf"), 
          plt, 
          nrow = 3, ncol = 3)


plts <- map(c("subgroup", "UPN"),
    ~plot_umap(sobj, .x))

plt <- plot_grid(plotlist = plts, nrow = 1, ncol = 2)
save_plot(file.path(outdir, "umaps_by_class.pdf"), 
          plt, 
          nrow = 1, ncol = 2)
```

Write out metadata
```{r} 
mdata_out <- get_metadata(sobj)
outname <- file.path("tables", paste0("malignant_metadata_", format(Sys.Date(), "%Y_%m_%d"), ".tsv.gz"))
write_tsv(mdata_out, outname)
```

## save neoplastic object

```{r}
saveRDS(sobj, file.path("objects", "malignant_sobj.rds"))
```

## markers

```{r}
sobj <- readRDS(file.path("objects", "malignant_sobj.rds"))
Idents(sobj) <- "RNA_snn_res.0.02"

mkrs <- FindAllMarkers(sobj, only.pos = TRUE)

write_tsv(mkrs, file.path(mkrs_dir, "res_0.02_malignant_cluster_markers.tsv"))
```

```{r}
markers <- read_tsv(file.path(mkrs_dir, "res_0.02_malignant_cluster_markers.tsv"))

list_of_markers <- split(markers, markers$cluster)
names(list_of_markers) <- str_c("cluster_", names(list_of_markers))
list_of_markers <- map(list_of_markers, 
                       ~set_xlsx_class(.x, "gene", "Text"))

readme_sheet <- data_frame(
  Columns = c(
  "Genes differentially expressed between each cluster and all other cells",
  "",
  "Columns",
  "pval",
  "avg_logFC",
  "pct.1",
  "pct.2",
  "p_val_adj",
  "cluster",
  "gene"
), Description = c(
  "",
  "",
  "",
  "p-value from wilcox test of indicated cluster compared to other clusters",
  "average fold change expressed in natural log",
  "percent of cells expressing gene (UMI > 0) in cluster",
  "percent of cell expressing gene (UMI > 0) in all other clusters",
  "Bonferroni corrected p-value",
  "cluster name",
  "gene name"
))
readme_sheet <- list(README = readme_sheet)
names(readme_sheet) <- "README"
openxlsx::write.xlsx(c(readme_sheet, 
                       list_of_markers),
                     "markers/malignant_cluster_markers.xlsx")

```


## Subset immune populations


```{r}
  
sobj <- readRDS(file.path("objects", "sobj.rds"))

immune_cells <- colnames(sobj)[sobj$cell_phenotype %in% c("Immune",
                                                          "Normal")]
sobj <- sobj[, immune_cells]
sobj <- FindVariableFeatures(sobj, 
                             selection.method = "vst", 
                             nfeatures = 3000, 
                             verbose = FALSE)

sobj <- ScaleData(sobj, 
                  vars.to.regress = c("percent.mt", "nCount_RNA"), 
                  verbose = TRUE)

sobj <- RunPCA(sobj, npcs = 40, verbose = FALSE)
sobj <- RunUMAP(sobj, 
                reduction = "pca", 
                dims = 1:40, 
                min.dist = 0.3, 
                n.neighbors = 30L)

sobj <- FindNeighbors(sobj,
                      reduction = "pca",
                      dims = 1:40,
                      k.param = 50)

sobj <- FindClusters(sobj, resolution = c(0.3, 0.1, 0.05, 0.02, .01))

outdir <- "figs/normal_subset"
dir.create(outdir, showWarnings = FALSE)

plts <- map(str_subset(colnames(sobj@meta.data), "RNA_snn"), 
            ~plot_umap(sobj, .x) + 
              labs(title = .x))

p_1 <- plot_umap(sobj, "subgroup") + labs(title = "Subgroup")
p_2 <- plot_umap(sobj, "cell_type") + labs(title = "Cell Type")
plts <- c(plts, list(p_1), list(p_2))

plt <- plot_grid(plotlist = plts, nrow = 3, ncol = 3)
save_plot(file.path(outdir, "umaps_by_resolution.pdf"), 
          plt, 
          nrow = 3, ncol = 3)


plts <- map(c("subgroup", "UPN", "cell_type"),
    ~plot_umap(sobj, .x))

plt <- plot_grid(plotlist = plts, nrow = 1, ncol = 3)
save_plot(file.path(outdir, "umaps_by_class.pdf"), 
          plt, 
          nrow = 1, ncol = 3)
```

## save object

```{r }
saveRDS(sobj, file.path("objects", "immune_sobj.rds"))
```


## Markers within cluster

```{r, eval = F}
Idents(sobj) <- "RNA_snn_res.0.05"

mkrs_between_samples <- map(unique(sort(sobj$RNA_snn_res.0.05)), 
    function(x) {
      
      tmp_obj <- subset(sobj, idents = x)
      Idents(tmp_obj) <- "subgroup"
      mkrs <- FindAllMarkers(tmp_obj,
                          only.pos = TRUE) %>% 
         filter(p_val_adj < 0.01)
      mkrs
    })

names(mkrs_between_samples) <- paste0("cluster_", unique(sort(sobj$RNA_snn_res.0.05)))

mkrs_between_samples_df <- bind_rows(mkrs_between_samples, 
                                  .id = "cluster")
write_tsv(mkrs_between_samples_df, 
          file.path(mkrs_dir, "normal_immune_subset_cluster_markers_between_subgroups.tsv"))

openxlsx::write.xlsx(mkrs_between_samples, 
                      file.path(mkrs_dir, "normal_immune_subset_cluster_markers_between_subgroups.xlsx"))
```