---
title: "InferCNV analysis"
author: "Kent Riemondy RBI"
date: "7/2/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libs, message=FALSE, warning=FALSE, echo=FALSE}
source("../R/utils.R")
library(future)
plan(strategy = "multicore", workers = 4)
options(future.globals.maxSize = 2 * 1024 ^ 3)

proj_dir <- here()
data_dir <- file.path(proj_dir, "data", "cellranger", "results")
doc_dir <- file.path(proj_dir, "docs")

fig_dir <- "figs"
mkrs_dir <- "markers"
inferCNV_dir <- "inferCNV"
walk(c(fig_dir,mkrs_dir, inferCNV_dir), dir.create, showWarnings = F)
```

```{r}
sobj <- readRDS(file.path("objects", "sobj.rds"))
```


```{r, inferCNV}
download.file("https://data.broadinstitute.org/Trinity/CTAT/cnv/gencode_v19_gene_pos.txt", 
              file.path(inferCNV_dir, "gene_ordering_file.txt"))


#downsample to ~1000 cells per patient to test function
set.seed(42)

smart_sample <- function(x, size){
  if (length(x) <= size){
    return(x)
  } else {
    return(sample(x, size))
  }
}

subsampled_cells <- sobj@meta.data %>% 
    tibble::rownames_to_column("cell") %>% 
    split(., .$UPN) %>% 
    map(., ~pull(.x, cell)) %>% 
    map(., smart_sample, size = 500) %>% 
  unlist()

sobj <- sobj[, subsampled_cells]

ids_to_cell_type <- c(
  "3" = "myeloid",
  "14" = "myeloid",
  "5" = "tcell",
  "9" = "bcell",
  "10" = "astrocytes",
  "19" = "oligodendrocytes",
  "16" = "fibroblast",
  "15" = "other") 
  
sobj$id <- ids_to_cell_type[as.character(sobj$seurat_clusters)]
sobj$id <- ifelse(is.na(sobj$id), 
                  paste0("malignant_", sobj$subgroup, ":", sobj$UPN), 
                  sobj$id)
out <- sobj@meta.data %>% 
  tibble::rownames_to_column("cell") %>% 
  select(cell, id)

write_tsv(out, file.path(inferCNV_dir, "cellAnnotations.txt"), col_names = FALSE)
# create the infercnv object

library(infercnv)
infercnv_obj <- CreateInfercnvObject(raw_counts_matrix=sobj@assays$RNA@counts,
                                    annotations_file= file.path(inferCNV_dir, "cellAnnotations.txt"),
                                    delim="\t",
                                    gene_order_file= file.path(inferCNV_dir, "gene_ordering_file.txt"),
                                    ref_group_names=c("other", 
                                                      "tcell",
                                                      "bcell", 
                                                      "myeloid",
                                                      "astrocytes",
                                                      "oligodendrocytes", 
                                                      "fibroblast"))

# reduce memory 
rm(sobj)
gc()

infercnv_obj <- infercnv::run(infercnv_obj,
                             cutoff=0.1,  # use 1 for smart-seq, 0.1 for 10x-genomics
                             out_dir=file.path(inferCNV_dir, "cnv_output_dir"),  # dir is auto-created for storing outputs
                             cluster_by_groups = TRUE,   # cluster
                             denoise = TRUE,
                             HMM = FALSE,
                             num_threads = 2
                             )

saveRDS(infercnv_obj, "infercnv.rds")

# infercnv_obj = infercnv::run(infercnv_obj,
#                              cutoff=0.1,  # use 1 for smart-seq, 0.1 for 10x-genomics
#                              out_dir="output_dir",  # dir is auto-created for storing outputs
#                              cluster_by_groups=T,   # cluster
#                              denoise=T,
#                              HMM=T,
#                              HMM_type='i6'
#                              )
```


```{r}
dat <- readRDS(file.path(inferCNV_dir, "cnv_output_dir", "run.final.infercnv_obj")) 

```